# Upload some file
POST http://localhost:3000/api/files/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="1.jpg"

< ./1.jpg

--boundary--

###

# Get file by ID
GET http://localhost:3000/api/files/65a3e33ea700fcea5b966364 HTTP/1.1

###
