# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound3.local",
  "dateBirth": "2012-02-22",
  "firstname": "Keks",
  "lastname": "Smith",
  "password": "123456"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/65a3c5ff796059daed5d8441 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAbm90Zm91bmQzLmxvY2FsIiwicm9sZSI6InVzZXIiLCJsYXN0bmFtZSI6IlNtaXRoIiwiZmlyc3RuYW1lIjoiS2VrcyIsImlhdCI6MTcwNTIzMTkyMiwiZXhwIjoxNzA1MjMyMzU0fQ.51a1XgHvqzcl0d_c8kd1ghORamAC6WroLZpyUGsMDTs

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound3.local",
  "password": "123456"
}

###

# Demo route for Pipe
GET http://localhost:3000/api/auth/demo/1 HTTP/1.1

###
